name: fashion_ecommerce_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  animate_do: ^3.0.2
  advance_notification: ^1.0.6
  firebase_auth: ^4.14.0
  badges: ^2.0.3
  line_icons: ^2.0.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  razorpay_flutter: ^1.3.5

 

  font_awesome_flutter: ^10.6.0
  pin_code_text_field: ^1.8.0
  curved_navigation_bar: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/profile_page_images/
    - assets/teamlogo.png
    - assets/box.png

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
        - asset: assets/fonts/AlegreyaSans-Medium.ttf




